name: Deploy to Surge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install & build
        run: |
          npm install
          npm run build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./ ${{ vars.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}